name: Run Screenshot Script

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the capture_screenshot.py script with arguments
      - name: Run capture_screenshot.py
        run: |
          python capture_screenshot.py "Sunoh (Google)" "last 5 days"
        
      # Step 5: Upload screenshot to GitHub (updated to v4)
      - name: Upload Screenshot as Artifact
        uses: actions/upload-artifact@v4  # Use v4 for the latest version
        with:
          name: screenshot
          path: full_screenshot.png
